# -*- coding: utf-8 -*-

"""
/***************************************************************************
 FdotCrash
                                 A QGIS plugin
 Test plugin for interfacing with public FDOT data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-01-25
        copyright            : (C) 2023 by Seth Willis Bassett
        email                : seth.bassett@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Seth Willis Bassett'
__date__ = '2023-01-25'
__copyright__ = '(C) 2023 by Seth Willis Bassett'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
import os
import inspect
from osgeo import gdal
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import (QCoreApplication, QVariant)
from qgis.core import (QgsMessageLog, 
                       QgsProcessing,
                       QgsFeatureSource,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterField,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterFileDestination)

from qgis.core import (QgsFeature,
                       QgsFeatureSink,
                       QgsFields,
                       QgsField,
                       QgsVectorLayer,
                       QgsGeometry,
                       QgsPointXY,
                       QgsWkbTypes,                                              
                       QgsFeatureRequest)


class AssignPointsToSegments(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    LINEWORK_ID = 'LINEWORK_ID'
    LINEWORK_BMP = 'LINEWORK_BMP'
    LINEWORK_EMP = 'LINEWORK_EMP'
    CRASHSOURCE = 'CRASHSOURCE'

    basePath = r'https://gis.fdot.gov/arcgis/rest/services/Crashes_All/FeatureServer/'
    listIds = ['All Crashes','Commercial Vehicle','Drivers 65+','Fatalities',
               'Injuries and Fatalities','Motorcycle / Moped','Bicyclist','Pedestrian',
               'Bridge','Two-way Left-Turn Lane','Work Zone','Dark Conditions',
               'Wet Weather','Aggressive Driving','Lane Change','Median Crossover',
               'Red Light Running','Speeding','Alcohol / Drug Use','Alcohol / Drugs Under Influence',
               'Seat Belt Not Used']
    urls = {'All Crashes': '0',
            'Commercial Vehicle': '1',
            'Drivers 65+': '2',
            'Fatalities': '3',
            'Injuries and Fatalities': '4',
            'Motorcycle / Moped': '5',
            'Bicyclist': '6',
            'Pedestrian': '7',
            'Bridge': '8',
            'Two-way Left-Turn Lane': '9',
            'Work Zone': '10',
            'Dark Conditions': '11',
            'Wet Weather': '12',
            'Aggressive Driving': '13',
            'Lane Change': '14',
            'Median Crossover': '15',
            'Red Light Running': '16',
            'Speeding': '17',
            'Alcohol / Drug Use': '18',
            'Alcohol / Drugs Under Influence': '19',
            'Seat Belt Not Used': '20'}

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                name=self.INPUT,
                description=self.tr('Input Lines'),
                types=[QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                name = self.LINEWORK_ID,
                description=self.tr('Roadway ID Column'),
                type=QgsProcessingParameterField.String,
                parentLayerParameterName=self.INPUT
                )
            )

        self.addParameter(
            QgsProcessingParameterField(
                name = self.LINEWORK_BMP,
                description=self.tr('Begin Milepost Column'),
                type=QgsProcessingParameterField.Numeric,
                parentLayerParameterName=self.INPUT
                )
            )

        self.addParameter(
            QgsProcessingParameterField(
                name = self.LINEWORK_EMP,
                description=self.tr('End Milepost Column'),
                type=QgsProcessingParameterField.Numeric,
                parentLayerParameterName=self.INPUT
                )
            )

        self.addParameter(
            QgsProcessingParameterEnum(
                name = self.CRASHSOURCE,
                description=self.tr('Crash Type'),
                options=self.listIds,
                defaultValue=0,
                optional=False)
                )

        # self.addParameter(
        #     QgsProcessingParameterFeatureSink(
        #         name = self.OUTPUT,
        #         description=self.tr('Output Lines'))
        #         )
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                self.tr('Output File'),
                'CSV files (*.csv)',
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        lines = self.parameterAsSource(parameters, self.INPUT, context)    
        idField = self.parameterAsString(parameters, self.LINEWORK_ID, context)
        bmpField = self.parameterAsString(parameters, self.LINEWORK_BMP, context)
        empField = self.parameterAsString(parameters, self.LINEWORK_EMP, context)
        
        crashLayerName = self.parameterAsString(parameters, self.CRASHSOURCE, context)        
        crashLayerUrl = os.path.join(self.basePath, crashLayerName)
        
        uri = f"crs='EPSG:26917' url='{crashLayerUrl}'"        
        source = QgsVectorLayer(uri, 'crashes', 'arcgisfeatureserver')

                
        fields = QgsFields()
        fields.append(QgsField(idField, QVariant.String))
        fields.append(QgsField(bmpField, QVariant.Double, 'double', 10, 0))
        fields.append(QgsField(empField, QVariant.Double, 'double', 10, 0))
        
        fieldnames = [field.name() for field in lines.fields()]
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT, context,
                                               fields, source.wkbType(), source.sourceCrs())


        

        #Compute the number of steps to display within the progress bar and
        #get features from source
        csv = self.parameterAsFileOutput(parameters, self.OUTPUT, context)
        fieldnames = [field.name() for field in source.fields()]
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        with open(csv, 'w') as output_file:
            # write header
            line = ','.join(name for name in fieldnames) + '\n'
            output_file.write(line)
            for current, f in enumerate(features):
                # Stop the algorithm if cancel button has been clicked
                if feedback.isCanceled():
                    break

                # Add a feature in the sink
                line = ','.join(str(f[name]) for name in fieldnames) + '\n'
                output_file.write(line)

                # Update the progress bar
                feedback.setProgress(int(current * total))
        return {self.OUTPUT: csv}
        

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Assign Crashes to Segments'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """        
        return 'Crash Assignment'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return AssignPointsToSegments()

    def icon(self):
        cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
        icon = QIcon(os.path.join(os.path.join(cmd_folder, 'icons/BasePointToSegment.svg')))
        return icon
